# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/CampusHubERP}
spring.data.mongodb.database=${MONGODB_DATABASE:CampusHubERP}

# REST Port configuration
server.port=${PORT:8080}

# Security Signatures
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
